version: "3"
services:
  pg_master:
    build: master
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PG_REP_USER=${DB_REP_USER}
      - PG_REP_PASSWORD=${DB_REP_PASS}
    ports:
      - "5432:5432"
    networks:
      default:
        aliases:
          - pg_cluster
  pg_slave:
    build: slave
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PG_REP_USER=${DB_REP_USER}
      - PG_REP_PASSWORD=${DB_REP_PASS}
      - PG_MASTER_HOST=pg_master
    ports:
      - "5433:5432"
    env_file:
      - .env
    networks:
      default:
        aliases:
          - pg_cluster
volumes:
  pg_data: